# Generated by Django 5.0.3 on 2024-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hoes_fucked',
            field=models.CharField(default='Left hand', max_length=200),
        ),
    ]
