# Generated by Django 5.0.3 on 2024-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_hoes_fucked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hoes_fucked',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='A person driven by art. That is me!', max_length=200),
        ),
    ]
