# Generated by Django 5.0.3 on 2024-04-04 19:57

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=99999, null=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='tid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh123456', length=10, max_length=30, prefix='Technique', unique=True),
        ),
    ]
