# Generated by Django 5.0.3 on 2024-04-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_tags_alter_product_old_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.AddField(
            model_name='artist',
            name='shortBio',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
