# Generated by Django 5.0.3 on 2024-04-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_old_price_artist_shortbio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='title',
            new_name='name',
        ),
    ]
