# Generated by Django 5.0.3 on 2024-04-05 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_title_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist', to='home.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='address',
            field=models.CharField(blank=True, default='25 Jump Street ...', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='authentic_rating',
            field=models.CharField(blank=True, default='Good', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='chat_resp_time',
            field=models.CharField(blank=True, default='Not much!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='days_return',
            field=models.CharField(blank=True, default='100', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, default='06 11 22 33 44', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='shipping_time',
            field=models.CharField(blank=True, default='not much', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='shortBio',
            field=models.TextField(max_length=50),
        ),
    ]
