# Generated by Django 5.0.3 on 2024-04-05 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_artist_alter_artist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.style'),
        ),
        migrations.AddField(
            model_name='artist',
            name='technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.technique'),
        ),
    ]
