# Generated by Django 5.0.3 on 2024-04-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_artist_style_artist_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='style',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technique',
        ),
        migrations.AddField(
            model_name='artist',
            name='style',
            field=models.ManyToManyField(blank=True, to='home.style'),
        ),
        migrations.AddField(
            model_name='artist',
            name='technique',
            field=models.ManyToManyField(blank=True, to='home.technique'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ManyToManyField(blank=True, to='home.style'),
        ),
        migrations.AddField(
            model_name='product',
            name='technique',
            field=models.ManyToManyField(blank=True, to='home.technique'),
        ),
    ]
