# Generated by Django 5.0.3 on 2024-04-06 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_artist_style_remove_artist_technique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.CharField(choices=[('Agadir', 'Agadir'), ('Al Hoceima', 'Al Hoceima'), ('Azilal', 'Azilal'), ('Beni Mellal', 'Beni Mellal'), ('Ben Slimane', 'Ben Slimane'), ('Berkane', 'Berkane'), ('Berrechid', 'Berrechid'), ('Boujdour', 'Boujdour'), ('Casablanca', 'Casablanca'), ('Chefchaouen', 'Chefchaouen'), ('Dakhla', 'Dakhla'), ('El Aaiun', 'El Aaiun'), ('El Hajeb', 'El Hajeb'), ('El Jadida', 'El Jadida'), ('Errachidia', 'Errachidia'), ('Essaouira', 'Essaouira'), ('Fes', 'Fes'), ('Figuig', 'Figuig'), ('Guelmim', 'Guelmim'), ('Ifrane', 'Ifrane'), ('Kénitra', 'Kénitra'), ('Khemisset', 'Khemisset'), ('Khénifra', 'Khénifra'), ('Khouribga', 'Khouribga'), ('Laâyoune', 'Laâyoune'), ('Larache', 'Larache'), ('Marrakech', 'Marrakech'), ('Meknès', 'Meknès'), ('Midelt', 'Midelt'), ('Mohammedia', 'Mohammedia'), ('Nador', 'Nador'), ('Ouarzazate', 'Ouarzazate'), ('Ouezzane', 'Ouezzane'), ('Oujda', 'Oujda'), ('Rabat', 'Rabat'), ('Safi', 'Safi'), ('Salé', 'Salé'), ('Sefrou', 'Sefrou'), ('Settat', 'Settat'), ('Sidi Ifni', 'Sidi Ifni'), ('Sidi Kacem', 'Sidi Kacem'), ('Sidi Slimane', 'Sidi Slimane'), ('Skhirat', 'Skhirat'), ('Tan-Tan', 'Tan-Tan'), ('Tanger', 'Tanger'), ('Taza', 'Taza'), ('Tétouan', 'Tétouan'), ('Tinghir', 'Tinghir'), ('Tiznit', 'Tiznit'), ('Youssoufia', 'Youssoufia')], default='City you live in', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='home.artist'),
        ),
    ]
