# Generated by Django 5.0.3 on 2024-04-11 22:16

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_productreview_product_artistreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Philosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh123456', length=10, max_length=30, prefix='Style', unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Philosophies',
            },
        ),
        migrations.CreateModel(
            name='SubjectMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh123456', length=10, max_length=30, prefix='SubjectMatter', unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Subjects Matter',
            },
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_reviews', to='home.artist'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='home.product'),
        ),
        migrations.AddField(
            model_name='artist',
            name='philosophy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.philosophy'),
        ),
        migrations.AddField(
            model_name='artist',
            name='subject_matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subjectmatter'),
        ),
    ]
