# Generated by Django 5.0.3 on 2024-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_cartorderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
