# Generated by Django 5.0.3 on 2024-04-27 18:46

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profileArtworkImage',
            field=models.ImageField(default='Image of your preferred artwork!', upload_to=home.models.user_directory_path),
        ),
    ]
