# Generated by Django 5.0.3 on 2024-04-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_artist_image_alter_artist_profileartworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product',
        ),
    ]
