# Generated by Django 5.0.3 on 2024-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_cartorderitems_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='item',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product_page',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
