# Generated by Django 5.0.3 on 2024-04-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_item_cartorderitems_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
