# Generated by Django 5.0.3 on 2024-05-01 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_userreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={'verbose_name_plural': 'User Reviews'},
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
