# Generated by Django 5.0.3 on 2024-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_address_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='medium',
            field=models.CharField(choices=[('canvas', 'Canvas'), ('paper', 'Fine Art Paper'), ('wood_panel', 'Wood Panel'), ('other', 'Other')], default='canvas', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='signed_by_artist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Description | Story | Meaning of the artwork according to the artist.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='A more detailed description of the tools used to paint the artwork.', null=True),
        ),
    ]
