# Generated by Django 5.0.3 on 2024-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_rename_status_product_available_product_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(choices=[('free', 'Free'), ('not_included', 'Not Included')], default='not_included', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In review'), ('published', 'Published')], default='in_review', max_length=30),
        ),
    ]
