# Generated by Django 5.0.3 on 2024-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_product_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.CharField(choices=[('free', 'Free'), ('not included', 'Not Included')], max_length=40),
        ),
    ]
