# Generated by Django 5.0.3 on 2024-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_product_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in review', 'In review'), ('published', 'Published')], default='in review', max_length=30),
        ),
    ]
