# Generated by Django 5.0.3 on 2024-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_product_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
