# Generated by Django 5.0.3 on 2024-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
