# Generated by Django 5.0.3 on 2024-05-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_artist_facebook_artist_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
