"""
Django settings for atlas project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-or@13ouxpm8d3axm((#c)6y#m+y!#0erk7ljb0=q7r7$8-!hy9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    #ngrok host to be able to test paypal's webhook (no longer using webhook)
    'localhost', 
    '127.0.0.1', 
    '.ngrok-free.app',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'https://.ngrok-free.app',
    'https://25c4-41-142-21-169.ngrok-free.app',
]

CORS_ORIGIN_WHITELIST = [
    'http://localhost',
    'http://127.0.0.1',
    'https://.ngrok-free.app',
]



# Application definition

INSTALLED_APPS = [
    # added jazzmin to customize admin page
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # custom apps where we'll put user authentication and whatnot
    'home',
    'userauths',
    'cities_light',
    'paypal.standard.ipn',
    'corsheaders',
    'phonenumber_field',
    'artist_dashboard',

    # Facebook & Google authentication
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # allauth 
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'atlas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.default',
            ],
        },
    },
]

WSGI_APPLICATION = 'atlas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

STATICFILES_DIRS = [os.path.join('static')]

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR,"media")
# We haven't added a media folder because it'll be created automatically


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    'site_brand' : "Artful Atlas",
    'site_logo' : "/images/logos-images/logo.png",
    'copyright' : "Artful Atlas",
}

AUTH_USER_MODEL = 'userauths.User'

PAYPAL_RECEIVER_EMAIL = 'sb-n6hkb29074012@business.example.com'

PAYPAL_TEST = True

# Force the paypal popup to work
SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'

# For google & facebook authentication
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'APP': {
            'client_id': '328479635001-fogkcfcucg5gl3bf6qcbr0bi1tn3552b.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}

# To skip the intermediate page
SOCIALACCOUNT_LOGIN_ON_GET=True

# Google and facebook cliend id & secret 

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '328479635001-fogkcfcucg5gl3bf6qcbr0bi1tn3552b.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_FACEBOOK_KEY = '455015673880666'
SOCIAL_AUTH_FACEBOOK_SECRET = '75af2f6c9027ae2d0fb4ca5facc1ae94'
